#!/usr/bin/env bash
# setup_cluster.sh — One-time cluster setup: generate nodes config, open firewall,
# and copy the binary + config files to every machine via plain SSH.
#
# Prerequisites:
#   1. SSH key at ~/.ssh/google_compute_engine (generated by gcloud on first use)
#   2. That public key added to GCP Console → Compute Engine → Metadata → SSH Keys
#   3. Firewall rule already created from Cloud Shell (ports 8000-8004)
#
# Run from the Sparse_Bullshark project root on node-0:
#   bash setup_cluster.sh

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────

BINARY="./target/release/sparse_bullshark"
NODES_PER_MACHINE=5          # ← change this to adjust total nodes (total = machines × this)
SSH_KEY="$HOME/.ssh/google_compute_engine"
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no -o LogLevel=ERROR"
USER="henriquecostavale"

# Machine internal IP list (order determines node ID assignment)
# With NODES_PER_MACHINE=5: 10 machines → 50 nodes total
MACHINE_IPS=(
    "10.164.0.12"   # node-0  → nodes  0-4
    "10.164.0.6"    # node-1  → nodes  5-9
    "10.164.0.11"   # node-2  → nodes 10-14
    "10.164.0.8"    # node-3  → nodes 15-19
    "10.164.0.9"    # node-4  → nodes 20-24
    "10.164.0.10"   # node-5  → nodes 25-29
    "10.164.0.13"   # node-6  → nodes 30-34
    "10.164.0.14"   # node-7  → nodes 35-39
    "10.164.0.15"   # node-8  → nodes 40-44
    "10.164.0.16"   # node-9  → nodes 45-49
)

# ── Build if needed ───────────────────────────────────────────────────────────

if [[ ! -f "$BINARY" ]]; then
    echo "==> Binary not found — building release binary..."
    cargo build --release
fi

# ── Generate distributed nodes.csv ───────────────────────────────────────────

DIST_CSV="./shared/nodes_distributed.csv"
echo "==> Generating $DIST_CSV (${#MACHINE_IPS[@]} machines × $NODES_PER_MACHINE nodes)..."
echo "id,host,port,behavior" > "$DIST_CSV"
node_id=0
for IP in "${MACHINE_IPS[@]}"; do
    for ((p=0; p<NODES_PER_MACHINE; p++)); do
        echo "$node_id,$IP,$((8000+p)),ok" >> "$DIST_CSV"
        node_id=$((node_id + 1))
    done
done
total_nodes=$node_id
echo "    Generated $total_nodes nodes."

# ── Copy files to each machine (in parallel) ──────────────────────────────────

setup_machine() {
    local IP=$1

    echo "==> [$IP] Creating directories..."
    ssh $SSH_OPTS "$USER@$IP" \
        "mkdir -p ~/Sparse_Bullshark/target/release ~/Sparse_Bullshark/shared"

    echo "==> [$IP] Copying binary..."
    scp $SSH_OPTS "$BINARY" \
        "$USER@$IP:~/Sparse_Bullshark/target/release/sparse_bullshark"

    echo "==> [$IP] Copying config files..."
    scp $SSH_OPTS "$DIST_CSV" \
        "$USER@$IP:~/Sparse_Bullshark/shared/nodes.csv"

    scp $SSH_OPTS "./shared/public_keys.toml" \
        "$USER@$IP:~/Sparse_Bullshark/shared/public_keys.toml"

    scp $SSH_OPTS "./keys" \
        "$USER@$IP:~/Sparse_Bullshark/keys"

    echo "==> [$IP] Making binary executable..."
    ssh $SSH_OPTS "$USER@$IP" \
        "chmod +x ~/Sparse_Bullshark/target/release/sparse_bullshark"

    echo "==> [$IP] Done."
}

for IP in "${MACHINE_IPS[@]}"; do
    setup_machine "$IP" &
done
wait

echo ""
echo "=== Cluster setup complete: $total_nodes nodes across ${#MACHINE_IPS[@]} machines ==="
echo ""
echo "Next: python3 run_distributed.py --tx-size 512 --n-tx 500 --mode prbc_sailfish --input-rate 20000"
